Repository UTM-Robotics/Deerhunt-Infrastructure, pull requests merged in 2021-06, with the labels that each got.

#15 Outfile removal and other small changes.
  README.md
  pytest/test_auth.py
  server/app.py
  server/config.py
  server/run.sh
  tests/README.md
  tests/ref/test_register.ref
  tests/test_auth.py
Labels: Testing

#16 Adds login page layout and api calls without response handling
  deerhunt/package-lock.json
  deerhunt/package.json
  deerhunt/src/pages/Login.css
  deerhunt/src/pages/Login.js
Labels: FrontEnd

#19 Development install script enhanced
  README.md
  install.sh
Labels: enhancement

#20 Alex registration route and email testing
  .gitignore
  server/Auth/codegenerator.py
  server/Auth/register.py
  server/Auth/verify.py
  server/EmailBot/emailbot.py
  server/EmailBot/registration.html
  server/app.py
  server/config.py
  server/requirements.txt
  server/run.sh
  tests/README.md
  tests/__init__.py
  tests/conftest.py
  tests/ref/test_register.ref
  tests/ref/test_register_email.ref
  tests/test_auth.py
  tests/testbase.py
Labels: Backend
